server {
    listen 80;

    # Navigation du Frontend React et gestion des routes SPA
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirection propre des requêtes vers l'API Schedulift au sein du cluster
    location /api/ {
        proxy_pass http://schedulift-api:3005;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Origin "http://localhost:5173";

        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}